apiVersion: v1
kind: Service
metadata:
  name: demo-app-ui
  namespace: demo-app
  labels:
    app: demo-app-ui
spec:
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: demo-app-ui
  type: ClusterIP
